"""input table

Revision ID: b2e795a12198
Revises: 
Create Date: 2020-04-26 12:18:46.735843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e795a12198'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Peptide', sa.String(), nullable=True),
    sa.Column('Protein', sa.String(), nullable=True),
    sa.Column('Hex', sa.Float(), nullable=True),
    sa.Column('HexNAc', sa.Float(), nullable=True),
    sa.Column('Fuc', sa.Float(), nullable=True),
    sa.Column('Sia', sa.Float(), nullable=True),
    sa.Column('Charge', sa.Float(), nullable=True),
    sa.Column('Deamidation', sa.Float(), nullable=True),
    sa.Column('Carbamido', sa.Boolean(), nullable=True),
    sa.Column('Disulfidebridges', sa.Float(), nullable=True),
    sa.Column('Resolution', sa.String(), nullable=True),
    sa.Column('Sodium', sa.Boolean(), nullable=True),
    sa.Column('Modification', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monomz', sa.String(), nullable=True),
    sa.Column('mostab', sa.String(), nullable=True),
    sa.Column('plot_url', sa.String(), nullable=True),
    sa.Column('composition', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('input')
    # ### end Alembic commands ###
